# Alacritty Configuration File (TOML format)
# font cache flush fc-cache -fv ~/.local/share/fonts


[font]
size = 12.0

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[window]
opacity = 0.8
option_as_alt = "Both"
dimensions = { columns = 130, lines = 40 }
title = "CodeBrandt"
dynamic_title = false

[colors.primary]
background = "0x1e1e1e"
foreground = "0xdcd7ba"

[colors.normal]
black = "0x1e1e2e"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xa9b1d6"

[colors.bright]
black = "0x414868"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xc0caf5"
