# Alacritty Configuration File (TOML format)

[font]
size = 14.0

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[window]
opacity = 1.0
option_as_alt = "Both"

[colors.primary]
background = "0x1e1e1e"
foreground = "0xdcd7ba"

[colors.normal]
black = "0x1e1e2e"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xa9b1d6"

[colors.bright]
black = "0x414868"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xc0caf5"
